### ISSUE TITLE
Page Navigation

### ISSUE THREAD

**Issue by Tom-Fang00** [JaredJCastro/TermProject#2]
I like how you separate the contents into different sections such as restaurant and disserts. However, I think it would be better if there is a better name for sitemap, or if there is another way to reach that page. I don't think that a normal person would understand what a sitemap is and thus missing those contents.

**Comment by Tom-Fang00** [comment]
Sorry, I just realized that the names on the main page are actually clickable, then I would suggest to change them in terms of font or color and make them stand out a bit, maybe using a list format. Just to make them more stand out as a navigation bar.

**Comment by JaredJCastro** [comment]
Thank you for the suggestion!
