### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by kreid1babsonedu** [JaredJCastro/TermProject#6]
I really liked your font choice and layout of your pages!
**technical issues/bugs/suggestions**
- For all you links in the sitemap, I would recommend adding them to your nav bar
- I would recommend removing the horizontal line on each page 

 **suggestions on content**
- more content variety other that images  
- Some links to places would be cool

**Comment by JaredJCastro** [comment]
Thanks for the suggestions!
